#!/usr/bin/env bash
# Regenerate the Supabase sandbox migration that installs pg_standard_webhooks as a
# Trusted Language Extension. Run after editing the extension's SQL or control file,
# then `supabase db reset` to apply it.
set -euo pipefail

root="$(cd "$(dirname "$0")/.." && pwd)"
control="$root/pg_standard_webhooks.control"
version="$(sed -nE "s/^default_version *= *'(.*)'/\1/p" "$control")"
comment="$(sed -nE "s/^comment *= *'(.*)'/\1/p" "$control")"
requires="$(sed -nE "s/^requires *= *'(.*)'/\1/p" "$control" | tr -d ' ')"
script="$root/pg_standard_webhooks--$version.sql"
out="$root/supabase/migrations/20261006000001_install_pg_standard_webhooks.sql"

if grep -q '\$_pgtle_\$' "$script"; then
    echo "error: $script contains the \$_pgtle_\$ quote tag" >&2
    exit 1
fi

{
    echo "-- GENERATED by scripts/generate-supabase-migration.sh from pg_standard_webhooks--$version.sql."
    echo "-- Do not edit by hand."
    echo
    echo "select pgtle.install_extension("
    echo "    'pg_standard_webhooks',"
    echo "    '$version',"
    echo "    '${comment//\'/\'\'}',"
    echo "\$_pgtle_\$"
    cat "$script"
    echo "\$_pgtle_\$,"
    echo "    '{$requires}'"
    echo ");"
    echo
    echo "create schema if not exists webhooks;"
    echo "create extension pg_standard_webhooks schema webhooks;"
} > "$out"

echo "wrote ${out#"$root"/}"
